- Components/Field/Configuration.php
- Components/FormConfiguration.php
- Components/Validation/Configuration.php
- Components/Validation/Email.php
- Components/Validation/NissInsz.php
- Controller/FormController.php
- DependencyInjection/Configuration.php
- DependencyInjection/EMSFormExtension.php
- Resources/config/routing/form.xml
- Resources/config/services.xml
- Resources/views/form-api/form.html.twig
- Service/FormClient.php
- composer.json
* Improvement: No magic resolution for classes, get them from a content field
* Improvement: Use a form instance to make it easy to change design of a form
* Improvement: use configurations
> Improvements: no magic, easy design, use config

- Controller/FormController.php
- Resources/config/routing/dev.xml
- Resources/config/routing/form.xml
- Resources/views/debug.html.twig
Add the following route for development:
/_emss/debug/%form_ouuid%
> feature develop route for form

- Components/Field/AbstractField.php
- Components/Field/Radio.php
- FormConfig/FieldChoicesConfig.php
- FormConfig/FieldConfig.php
- FormConfig/FormConfig.php
- FormConfig/FormConfigFactory.php
- FormConfig/ValidationConfig.php
- Resources/config/services.xml
- add radio field component
- fields can have choices defined
- add logging for building the formConfig
- fields can have default value
> Add logging and radio type

- Controller/FormController.php
- Resources/views/form.html.twig
improve the rendering of the json response
> hotfix: form ajax returns invalid json

- Components/ValueObject/EmailMultiple.php
Set the HTML5 mode for the email constraint validation
> fix(Validation/EmailMultiple): set HTML5 mode to the email constraint

- .github/pull_request_template.md
|Bug fix?       |yes|
|New feature?   |no|	
Replace_With_One_Paragraph_Description
> maintain(merge master): develop out of date

- composer.json
|New feature?   |no|	
ClientHelper bundle 3.3
> Release  1.2.5

- Resources/doc/example.md
|Bug fix?        |no|
|New feature?   |no|	
|Fixed tickets  |no|
> Update readme: iframe url (#82)

- Components/Field/MultipleFile.php
Multiple is a from option not a attribute
> bug(form): multiple files upload (#89)

- Resources/doc/example.md
|Fixed tickets  |N|	
Just a better doc about the callback functions
> docs: js callback functions

- Submission/AbstractHandleResponse.php
> feat: AbstractHandleResponse extra data (#100)

- Components/Field/AbstractField.php
> fix: textarea counter issue (#102)

- Controller/AbstractFormController.php
- Controller/DebugController.php
- Controller/FormController.php
- DependencyInjection/Configuration.php
- DependencyInjection/EMSFormExtension.php
- FormConfig/FormConfig.php
- FormConfig/FormConfigFactory.php
- Resources/views/debug/form.html.twig
|New feature?   |yes|	
Attach a custom form template on the form instance.
They field on the form instance is called 'form_template' by default.
> release: 1.2.12

- Submission/AbstractHandleResponse.php
|New feature?   |no|	
refactor: setExtraData -> setExtra
> release: 1.2.13

- Components/EventSubscriber/NestedChoiceEventSubscriber.php
> fix: Avoid not iterable $data variable

- Resources/views/form_theme.html.twig
> hotfix: ems_send_confirmation_widget form(form)

- FormConfig/FormConfigFactory.php
- Resources/config/services.xml
|New feature?   |yes|	
|Fixed tickets  |no|
> release: 1.12.20

- FormConfig/FormConfigFactory.php
- Resources/config/services.xml
> Release 1.12.21

- Components/Constraint/IsRequiredIf.php
- Components/Constraint/IsRequiredIfValidator.php
- Components/Validation/RequiredIf.php
- DependencyInjection/Configuration.php
- DependencyInjection/EMSFormExtension.php
- FormConfig/FormConfigFactory.php
- Resources/config/services.xml
- Resources/doc/validations.md
- composer.json
|Bug fix?       |yes|
|New feature?   |yes|	
|Fixed tickets  |no|
> Release 1.12.22

- Components/Constraint/IsNissInsz.php
- Resources/translations/validators.de.xlf
- Resources/translations/validators.fr.xlf
- Resources/translations/validators.nl.xlf
> fix: better validation translations

- Components/Constraint/IsRequiredIfValidator.php
> Fix: empty strings and empty arrayd are not valid for required fields

- Components/Constraint/IsExpression.php
- Components/Constraint/IsExpressionValidator.php
- Components/Validation/Expression.php
- Resources/config/services.xml
- Resources/doc/validations.md
|Fixed tickets  |N|	
Add a validation using the ExpressionLanguage Component in the value.
> feat(validation): expression validation

- Components/Constraint/IsExpression.php
- Components/Constraint/IsExpressionValidator.php
- Components/Validation/Expression.php
- Resources/config/services.xml
- Resources/doc/validations.md
|Bug fix?       ||
* feat(validation): expression validation
> feat(validation): expression validation (#147)

- Resources/translations/messages.de.xlf
- Resources/translations/messages.en.xlf
- Resources/translations/messages.fr.xlf
- Resources/translations/messages.nl.xlf
- Resources/views/iframe.html.twig
|Bug fix?       |wcag fix|
title in iframe head
> fix: iframe meta title (#150)

- Components/Constraint/IsExpressionValidator.php
- Components/Constraint/IsVerificationCode.php
- Components/Constraint/IsVerificationCodeValidator.php
- Resources/config/services.xml
- Resources/translations/validators.de.xlf
- Resources/translations/validators.fr.xlf
- Resources/translations/validators.nl.xlf
- Service/Verification/VerificationService.php
- composer.json
|New feature?   |yes|	
Expression language from commonBundle with date support
> Release: 1.12.29

- Resources/translations/validators.en.xlf
En translations for validators
> fix: validators en translations (#161)

- Controller/ConfirmationController.php
Show origin field that generated a confirmation request. Add error status for our backend.
'code-field' = name of the source field send by the requestor
'ems-status' = 200 on success, 403 on guard check failure, 500 on every other error
ems-status will be 200 if the external service (e.g. sms send client) returns an error.
> fix: differentiante source and error source of confirmations

- Controller/ConfirmationController.php
|Bug fix?       |T|
confirmation response status and field
> fix: differentiante source and error source of confirmations (#163)

- Service/Confirmation/Endpoint/HttpEndpointType.php
Workaround for verification code leading 0 bug
> fix: workarount, prevent leading 0 in verification code

- Service/Confirmation/Endpoint/HttpEndpointType.php
Workaround leading 0 verification
> fix: workarount, prevent leading 0 in verification code (#165)

- Submission/FormDataFile.php
> fix: Avoid duplicates in form submission file

- Resources/views/form_theme.html.twig
- Submission/FormDataFile.php
fix: Avoid duplicates in form submission file
fix: Move file ems file label in a label twig block
> Release 1.12.35

- Security/Guard.php
- Security/HashcashToken.php
Improve handling of the hashcash token
> fix: bind hashcash validation to the current session

- Resources/views/form_theme.html.twig
|Fixed tickets  |N|	
The template was overriding the bootstrap4 template but it as to work with all template
> fix: Better intergation (bootstrap version independent)

- Submission/AbortHandleResponse.php
- Submission/Client.php
Allow to abort handling of submissions
> fix: allow termination of handling (#177)

- Resources/assets/js/backend.js
- Resources/assets/js/dynamicFields.js
- Resources/assets/js/form.js
- Resources/assets/js/formDebug.js
- Resources/assets/js/validation.js
- babel.config.js
- package-lock.json
- package.json
> ref: @babel -polyfill to -runtime

- Controller/ConfirmationController.php
- Controller/FormController.php
- Security/Guard.php
> fix(hashcash): form and json validation

- Controller/ConfirmationController.php
- Controller/FormController.php
- Security/Guard.php
> fix(hashcash): form and json validation (#192)

- DependencyInjection/Configuration.php
> fix(config): endpoints default value

- composer.json
- Upgrade Twig 2.14
https://github.com/ems-project/website-skeleton/issues/37
> Release 1.12.50

- composer.json
> chore: require emsch 3.4

- doc/example.md
|Bug fix?       ||
Replace_With_One_Paragraph_Description
> doc: no more manifest.json

- .github/workflows/commit_quality.yml
> ci: Add Commit quality yml

- .github/workflows/code_quality.yml
- composer.json
- package-lock.json
- src/DependencyInjection/Configuration.php
- src/Form/Extension/ConfirmationExtension.php
- src/Form/Extension/FieldExtension.php
- deprecations (#236)
- npm audit fix
> build: 1.12.59

- src/Resources/translations/validators.de.xlf
> fix: copy check in german

- src/Resources/translations/validators.de.xlf
> build: 1.12.60

- src/Components/Constraint/IsBirthDate.php
- src/Components/Constraint/IsBirthDateValidator.php
- src/Components/Validation/AbstractValidation.php
- src/Components/Validation/BirthDate.php
- src/FormConfig/FormConfigFactory.php
- src/FormConfig/ValidationConfig.php
- src/Resources/translations/validators.de.xlf
- src/Resources/translations/validators.en.xlf
- src/Resources/translations/validators.fr.xlf
- src/Resources/translations/validators.nl.xlf
|Bug fix?       ||
|Fixed tickets  ||
> feat: bday validation

- src/Components/Constraint/IsBirthDate.php
- src/Components/Constraint/IsBirthDateValidator.php
- src/Components/Validation/AbstractValidation.php
- src/Components/Validation/BirthDate.php
- src/FormConfig/FormConfigFactory.php
- src/FormConfig/ValidationConfig.php
- src/Resources/translations/validators.de.xlf
- src/Resources/translations/validators.en.xlf
- src/Resources/translations/validators.fr.xlf
- src/Resources/translations/validators.nl.xlf
|Bug fix?       ||
- feat: birthday in the past validator
- feat: add fieldName to validators
> build: 1.12.61

- composer.json
- src/Controller/AbstractFormController.php
- src/Controller/DebugController.php
- src/Controller/FormController.php
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/EMSFormExtension.php
- src/FormConfig/FormConfig.php
- src/FormConfig/FormConfigFactory.php
- src/Resources/config/services.xml
- src/Submission/Client.php
> build: 1.12.66

- .github/workflows/code_quality.yml
- .gitignore
- .php-cs-fixer.dist.php
- composer.json
- phpstan.neon.dist
- phpunit.xml.dist
- src/Components/ValueObject/BelgiumPhoneNumber.php
- src/Components/ValueObject/RrNumber.php
- src/Submission/AbstractHandleResponse.php
Fix Symfony deps + update phpcs
> fix: align symfony deps

- .github/workflows/code_quality.yml
- .gitignore
- .php-cs-fixer.dist.php
- composer.json
- phpstan.neon.dist
- phpunit.xml.dist
- src/Components/ValueObject/BelgiumPhoneNumber.php
- src/Components/ValueObject/RrNumber.php
- src/Submission/AbstractHandleResponse.php
> build: 1.12.67

- src/DependencyInjection/Configuration.php
- src/FormConfig/FormConfigFactory.php
> fix: - are  not easily manageable in yaml attribute

- src/DependencyInjection/Configuration.php
- src/FormConfig/FormConfigFactory.php
> build: 1.12.68

- src/FormConfig/FormConfig.php
- src/FormConfig/FormConfigFactory.php
- fix a loop on every form item instead of a top level loop
- add json markup support
> feat: markup from json

- composer.json
- doc/tips.md
- src/FormConfig/FieldChoicesConfig.php
- src/Submission/FormData.php
- files as uuid
- helper to get choice's label
> feat: files as UUID

- composer.json
- doc/tips.md
- src/FormConfig/FieldChoicesConfig.php
- src/Submission/FormData.php
> build: 1.12.70

- README.md
|Fixed tickets  |N|	
fix documentation links in the readme file
> fix: readme documentation links

- src/Components/Field/AbstractField.php
- src/Form/Extension/FieldExtension.php
- src/FormConfig/FieldConfig.php
- src/FormConfig/FormConfigFactory.php
> feat: add the json as meta when the form is loaded from json

- src/Components/Field/Submit.php
- src/Form/Extension/FieldExtension.php
> feat: extends submit

- src/Resources/views/form.html.twig
- src/Resources/views/form_theme.html.twig
- src/Resources/views/nested_choice_form.html.twig
> build: 1.12.75

- src/Submission/FormData.php
> fix: if a field contains an array of files

- src/Submission/FormData.php
> build: 1.13.1
